### ISSUE TITLE
Unable to use checkpoints for inference

### ISSUE THREAD

**Issue by talha1503** [thunlp/BERT-KPE#13]
I was trying to use the checkpoints provided for inference on openkp dataset, but I am getting this error for bert-base-cased:

```
RuntimeError: Error(s) in loading state_dict for BertForChunkTFRanking:                                                         
Missing key(s) in state_dict: "bert.embeddings.position_ids".
```

For roberta-base: 

```
RuntimeError: Error(s) in loading state_dict for RobertaForChunkTFRanking:                                                      
Missing key(s) in state_dict: "roberta.embeddings.position_ids".
``` 

I am using transformers==4.12.3 and pytorch==1.8 as mentioned in the requirements.txt file.

**Comment by SunSiShining** [comment]
Sorry for our late response. We have fixed the bug!

Recently we updated multilingual implementation (using the new Transformer Package) but ignored the testing of previous checkpoints. Now we restored the old version of Transformer and the folder of this package has been placed in our code (without installing the Transformer package)

Please clean up the Conda environment to infer the checkpoints. 

```
python 3.8
conda install --file conda-requirements.txt
pip install -r pip-requirements.txt
```

For any other questions please contact me via email s-sun17@mails.tsinghua.edu.cn
I check email almost every day :)

**Comment by talha1503** [comment]
Thank you very much for your assistance! The code is working fine now 😄

**Comment by SunSiShining** [comment]
And thank you very much for your issue : DSi发自我的iPhone------------------ Original ------------------From: Talha Chafekar  ***@***.***>Date: Sat,Dec 18,2021 3:10 AMTo: thunlp/BERT-KPE ***@***.***>Cc: SiSun ***@***.***>, Comment ***@***.***>Subject: Re: [thunlp/BERT-KPE] Unable to use checkpoints for inference (Issue#13)
Thank you very much for your assistance! The code is working fine now 😄

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/thunlp/BERT-KPE/issues/13#issuecomment-996971669",
"url": "https://github.com/thunlp/BERT-KPE/issues/13#issuecomment-996971669",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SunSiShining** [comment]
And thank you very much for your issue : D

**Comment by alpcansoydas** [comment]
You must use strict=False parameter when loading model weights:
`model.load_state_dict(torch.load(path, map_location=torch.device('cpu')), strict=False)`
