### ISSUE TITLE
API for key phrase extraction inference

### ISSUE THREAD

**Issue by jackjyzhang** [thunlp/BERT-KPE#16]
Currently the provided code (test.py) evaluates a pretrained checkpoint on datasets such as OpenKP. Is there an API where the input is some arbitrary text and the outputs are the extracted keywords, or tutorials on how to adapt the current code to do that? Thank you very much!

**Comment by SunSiShining** [comment]
Sorry for the late reply.

Currently, our code only customizes the interface of KP20k and OpenKP datasets. If you don't want to modify the code extensively, it is recommended that you preprocess your dataset into the format of KP20k (using stemming) and OpenKP (not using), and then train and test the KPE model.

You can refer to the preprocessing code we provide.
======
For any other questions, feel free to create an issue, and we will try our best to solve it.
If the problem is more urgent, you can send an email `s-sun17@mails.tsinghua.edu.cn` to me at the same time (I check email almost every day :).
